modLoader="javafml"
loaderVersion="[36,)"
license="All rights reserved"

[[mods]]
modId="chaosskeleton"
version="${file.jarVersion}"
displayName="Chaos Skeleton"
description="A Minecraft mod that adds chaos skeletons to the game."

[[dependencies.chaosskeleton]]
modId="forge"
mandatory=true
versionRange="[36,)"
ordering="NONE"
side="BOTH"

[[dependencies.chaosskeleton]]
modId="minecraft"
mandatory=true
versionRange="[1.19.2]"
ordering="NONE"
side="BOTH"